name: Release - Github Pages Deployment

on:
  release:
    types: [published]

jobs:
  build:
    name: Builds and uploads Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build the docs
        run: npm run docs

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/browser

  deploy:
    name: Deploys the artifact to Github Pages
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
